<?php

namespace Database\Seeders;

use App\Models\ReferenceData;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class ReferenceDataSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $data = [

            'employmentTypes' => [
                ['value' => 'Full Time', 'tamil_name' => 'முழுநேரம்'],
                ['value' => 'Part Time', 'tamil_name' => 'பகுதிநேரம்'],
                ['value' => 'Freelance', 'tamil_name' => 'தனிப்பட்ட வேலை'],
                ['value' => 'Internship', 'tamil_name' => 'பயிற்சி வேலை'],
                ['value' => 'Contract', 'tamil_name' => 'ஒப்பந்த வேலை'],
                ['value' => 'Temporary', 'tamil_name' => 'தற்காலிகம்'],
                ['value' => 'Volunteer', 'tamil_name' => 'தன்னார்வம்'],
                ['value' => 'Apprenticeship', 'tamil_name' => 'பயிற்சி வேலை'],
                ['value' => 'Seasonal', 'tamil_name' => 'பருவ வேலை'],
                ['value' => 'Other', 'tamil_name' => 'மற்றவை'],
            ],

            'maritalStatuses' => [
                ['value' => 'Single', 'tamil_name' => 'தனிமை'],
                ['value' => 'Married', 'tamil_name' => 'திருமணமானவர்'],
                ['value' => 'Divorced', 'tamil_name' => 'விவாகரத்து பெற்றவர்'],
                ['value' => 'Widowed', 'tamil_name' => 'விதவை'],
                ['value' => 'Separated', 'tamil_name' => 'பிரிந்தவர்'],
                ['value' => 'In a Relationship', 'tamil_name' => 'உறவில் உள்ளவர்'],
                ['value' => 'Engaged', 'tamil_name' => 'நிச்சயதார்த்தம்'],
            ],

            'bodyTypes' => [
                ['value' => 'Slim', 'tamil_name' => 'மெல்லிய'],
                ['value' => 'Athletic', 'tamil_name' => 'விளையாட்டு உடல்'],
                ['value' => 'Average', 'tamil_name' => 'சராசரி'],
                ['value' => 'Heavy', 'tamil_name' => 'கனமான'],
            ],

            'complexions' => [
                ['value' => 'Fair', 'tamil_name' => 'வெள்ளை'],
                ['value' => 'Medium', 'tamil_name' => 'மிதமான'],
                ['value' => 'Dark', 'tamil_name' => 'கருப்பு'],
            ],

            'languagesKnown' => [
                ['value' => 'Tamil', 'tamil_name' => 'தமிழ்'],
                ['value' => 'English', 'tamil_name' => 'ஆங்கிலம்'],
                ['value' => 'Hindi', 'tamil_name' => 'இந்தி'],
                ['value' => 'Telugu', 'tamil_name' => 'தெலுங்கு'],
                ['value' => 'Kannada', 'tamil_name' => 'கன்னடம்'],
                ['value' => 'Malayalam', 'tamil_name' => 'மலையாளம்'],
                ['value' => 'Bengali', 'tamil_name' => 'பெங்காலி'],
                ['value' => 'Marathi', 'tamil_name' => 'மராத்தி'],
                ['value' => 'Gujarati', 'tamil_name' => 'குஜராத்தி'],
                ['value' => 'Punjabi', 'tamil_name' => 'பஞ்சாபி'],
                ['value' => 'Urdu', 'tamil_name' => 'உருது'],
                ['value' => 'Oriya', 'tamil_name' => 'ஒரியா'],
                ['value' => 'Assamese', 'tamil_name' => 'அசாமி'],
                ['value' => 'Sanskrit', 'tamil_name' => 'சமஸ்கிருதம்'],
                ['value' => 'Tulu', 'tamil_name' => 'துலு'],
                ['value' => 'Konkani', 'tamil_name' => 'கொங்கணி'],
                ['value' => 'Sindhi', 'tamil_name' => 'சிந்தி'],
                ['value' => 'Dogri', 'tamil_name' => 'டோக்ரி'],
                ['value' => 'Kashmiri', 'tamil_name' => 'காஷ்மீரி'],
            ],

            'smokingHabits' => [
                ['value' => 'Non-smoker', 'tamil_name' => 'புகை பிடிக்காதவர்'],
                ['value' => 'Occasional smoker', 'tamil_name' => 'வழக்கமான புகை பிடிப்பவர்'],
                ['value' => 'Regular smoker', 'tamil_name' => 'தினசரி புகை பிடிப்பவர்'],
            ],

            'drinkingHabits' => [
                ['value' => 'Non-drinker', 'tamil_name' => 'மது அருந்தாதவர்'],
                ['value' => 'Social drinker', 'tamil_name' => 'சமூகமாக அருந்துபவர்'],
                ['value' => 'Regular drinker', 'tamil_name' => 'தினசரி அருந்துபவர்'],
            ],

            'religions' => [
                ['value' => 'Hindu', 'tamil_name' => 'இந்து'],
                ['value' => 'Muslim', 'tamil_name' => 'முஸ்லிம்'],
                ['value' => 'Christian', 'tamil_name' => 'கிறிஸ்துவர்'],
                ['value' => 'Buddhist', 'tamil_name' => 'பௌத்தர்'],
                ['value' => 'Sikh', 'tamil_name' => 'சிக்கள்'],
                ['value' => 'Jewish', 'tamil_name' => 'யூதர்'],
                ['value' => 'Other', 'tamil_name' => 'மற்றவை'],
            ],

            'dietaryPreferences' => [
                ['value' => 'Vegetarian', 'tamil_name' => 'சைவம்'],
                ['value' => 'Non-Vegetarian', 'tamil_name' => 'அசைவம்'],
                ['value' => 'Eggetarian', 'tamil_name' => 'முட்டை சைவம்'],
                ['value' => 'Vegan', 'tamil_name' => 'வீகன்'],
                ['value' => 'Pescatarian', 'tamil_name' => 'மீன் சைவம்'],
                ['value' => 'Gluten-Free', 'tamil_name' => 'குளூட்டன் இல்லாதது'],
                ['value' => 'Keto', 'tamil_name' => 'கீட்டோ'],
                ['value' => 'Paleo', 'tamil_name' => 'பாலியோ'],
                ['value' => 'Halal', 'tamil_name' => 'ஹலால்'],
                ['value' => 'Kosher', 'tamil_name' => 'கோஷர்'],
                ['value' => 'No Preferences', 'tamil_name' => 'விருப்பமில்லை'],
            ],

            'salaries' => [
                ['value' => 'Below 10,000', 'tamil_name' => '10,000 க்குக் கீழ்'],
                ['value' => '10,000 - 20,000', 'tamil_name' => '10,000 - 20,000'],
                ['value' => '20,000 - 30,000', 'tamil_name' => '20,000 - 30,000'],
                ['value' => '30,000 - 40,000', 'tamil_name' => '30,000 - 40,000'],
                ['value' => '40,000 - 50,000', 'tamil_name' => '40,000 - 50,000'],
                ['value' => '50,000 - 60,000', 'tamil_name' => '50,000 - 60,000'],
                ['value' => '60,000 - 70,000', 'tamil_name' => '60,000 - 70,000'],
                ['value' => '70,000 - 80,000', 'tamil_name' => '70,000 - 80,000'],
                ['value' => '80,000 - 90,000', 'tamil_name' => '80,000 - 90,000'],
                ['value' => '90,000 - 1,00,000', 'tamil_name' => '90,000 - 1,00,000'],
                ['value' => '1,00,000 - 1,50,000', 'tamil_name' => '1,00,000 - 1,50,000'],
                ['value' => '1,50,000 - 2,00,000', 'tamil_name' => '1,50,000 - 2,00,000'],
                ['value' => '2,00,000 - 2,50,000', 'tamil_name' => '2,00,000 - 2,50,000'],
                ['value' => '2,50,000 - 3,00,000', 'tamil_name' => '2,50,000 - 3,00,000'],
                ['value' => '3,00,000 - 3,50,000', 'tamil_name' => '3,00,000 - 3,50,000'],
                ['value' => '3,50,000 - 4,00,000', 'tamil_name' => '3,50,000 - 4,00,000'],
                ['value' => '4,00,000 - 4,50,000', 'tamil_name' => '4,00,000 - 4,50,000'],
                ['value' => '4,50,000 - 5,00,000', 'tamil_name' => '4,50,000 - 5,00,000'],
                ['value' => '5,00,000 - 6,00,000', 'tamil_name' => '5,00,000 - 6,00,000'],
                ['value' => '6,00,000 Above', 'tamil_name' => '6,00,000 மேல்'],
                ['value' => 'Not Specified', 'tamil_name' => 'குறிப்பிடப்படவில்லை'],
            ],

            'heights' => array_map(fn($v) => ['value' => $v, 'tamil_name' => $v], [
                '4ft - 121 cm', '4ft 1in - 124 cm', '4ft 2in - 127 cm', '4ft 3in - 130 cm',
                '4ft 4in - 133 cm', '4ft 5in - 136 cm', '4ft 6in - 139 cm', '4ft 7in - 142 cm',
                '4ft 8in - 145 cm', '4ft 9in - 148 cm', '4ft 10in - 151 cm', '4ft 11in - 154 cm',
                '4ft 12in - 157 cm', '5ft - 160 cm', '5ft 1in - 163 cm', '5ft 2in - 166 cm',
                '5ft 3in - 169 cm', '5ft 4in - 172 cm', '5ft 5in - 175 cm', '5ft 6in - 178 cm',
                '5ft 7in - 181 cm', '5ft 8in - 184 cm', '5ft 9in - 187 cm', '5ft 10in - 190 cm',
                '5ft 11in - 193 cm', '5ft 12in - 196 cm', '6ft - 199 cm', '6ft 1in - 202 cm',
                '6ft 2in - 205 cm', '6ft 3in - 208 cm', '6ft 4in - 211 cm', '6ft 5in - 214 cm',
                '6ft 6in - 217 cm', '6ft 7in - 220 cm', '6ft 8in - 223 cm', '6ft 9in - 226 cm',
                '6ft 10in - 229 cm', '6ft 11in - 232 cm', '6ft 12in - 235 cm', '7ft - 238 cm',
                '7ft 1in - 241 cm', '7ft 2in - 244 cm', '7ft 3in - 247 cm', '7ft 4in - 250 cm',
                '7ft 5in - 253 cm', '7ft 6in - 256 cm', '7ft 7in - 259 cm', '7ft 8in - 262 cm',
                '7ft 9in - 265 cm', '7ft 10in - 268 cm', '7ft 11in - 271 cm', '7ft 12in - 274 cm',
                '8ft - 277 cm', '8ft 1in - 280 cm', '8ft 2in - 283 cm', '8ft 3in - 286 cm',
                '8ft 4in - 289 cm', '8ft 5in - 292 cm', '8ft 6in - 295 cm'
            ]),

            'industries' => [
                ['value' => 'Accounting', 'tamil_name' => 'கணக்கியல்'],
                ['value' => 'Advertising', 'tamil_name' => 'விளம்பரம்'],
                ['value' => 'Aerospace', 'tamil_name' => 'வான்வெளி தொழில்'],
                ['value' => 'Agriculture', 'tamil_name' => 'விவசாயம்'],
                ['value' => 'Automotive', 'tamil_name' => 'மோட்டார் வாகனங்கள்'],
                ['value' => 'Banking', 'tamil_name' => 'வங்கி'],
                ['value' => 'Biotechnology', 'tamil_name' => 'உயிர் தொழில்நுட்பம்'],
                ['value' => 'Broadcast Media', 'tamil_name' => 'ஒளிபரப்புத் துறை'],
                ['value' => 'Building Materials', 'tamil_name' => 'கட்டிடப் பொருட்கள்'],
                ['value' => 'Business Supplies and Equipment', 'tamil_name' => 'வணிக உபகரணங்கள்'],
                ['value' => 'Chemicals', 'tamil_name' => 'இரசாயனங்கள்'],
                ['value' => 'Civic and Social Organization', 'tamil_name' => 'சமூக மற்றும் குடியியல் அமைப்புகள்'],
                ['value' => 'Civil Engineering', 'tamil_name' => 'சிவில் இன்ஜினியரிங்'],
                ['value' => 'Commercial Real Estate', 'tamil_name' => 'வணிக நிலம்'],
                ['value' => 'Computer and Network Security', 'tamil_name' => 'கணினி மற்றும் நெட்வொர்க் பாதுகாப்பு'],
                ['value' => 'Computer Games', 'tamil_name' => 'கணினி விளையாட்டுகள்'],
                ['value' => 'Computer Hardware', 'tamil_name' => 'கணினி உபகரணங்கள்'],
                ['value' => 'Computer Networking', 'tamil_name' => 'கணினி நெட்வொர்கிங்'],
                ['value' => 'Computer Software', 'tamil_name' => 'கணினி மென்பொருள்'],
                ['value' => 'Construction', 'tamil_name' => 'கட்டுமானம்'],
                ['value' => 'Consumer Electronics', 'tamil_name' => 'நுகர்வோர் மின்னணு சாதனங்கள்'],
                ['value' => 'Consumer Goods', 'tamil_name' => 'நுகர்வோர் பொருட்கள்'],
                ['value' => 'Consumer Services', 'tamil_name' => 'நுகர்வோர் சேவைகள்'],
                ['value' => 'Cosmetics', 'tamil_name' => 'அழகு சாதனங்கள்'],
                ['value' => 'Dairy', 'tamil_name' => 'பால்தொழில்'],
                ['value' => 'Defense and Space', 'tamil_name' => 'பாதுகாப்பு மற்றும் விண்வெளி'],
                ['value' => 'Design', 'tamil_name' => 'வடிவமைப்பு'],
                ['value' => 'Education Management', 'tamil_name' => 'கல்வி நிர்வாகம்'],
                ['value' => 'E-Learning', 'tamil_name' => 'மின்னியல் கல்வி'],
                ['value' => 'Electrical and Electronic Manufacturing', 'tamil_name' => 'மின்னியல் மற்றும் மின்னணு உற்பத்தி'],
                ['value' => 'Entertainment', 'tamil_name' => 'மகிழ்ச்சி'],
                ['value' => 'Environmental Services', 'tamil_name' => 'சுற்றுச்சூழல் சேவைகள்'],
                ['value' => 'Events Services', 'tamil_name' => 'நிகழ்ச்சி சேவைகள்'],
                ['value' => 'Executive Office', 'tamil_name' => 'நிர்வாக அலுவலகம்'],
                ['value' => 'Facilities Services', 'tamil_name' => 'வசதிகள் சேவைகள்'],
                ['value' => 'Farming', 'tamil_name' => 'விவசாயம்'],
                ['value' => 'Financial Services', 'tamil_name' => 'நிதி சேவைகள்'],
                ['value' => 'Fine Art', 'tamil_name' => 'நுண்கலை'],
                ['value' => 'Fishery', 'tamil_name' => 'மீன்வளத் துறை'],
                ['value' => 'Food and Beverages', 'tamil_name' => 'உணவு மற்றும் பானங்கள்'],
                ['value' => 'Food Production', 'tamil_name' => 'உணவு உற்பத்தி'],
                ['value' => 'Fund-Raising', 'tamil_name' => 'நிதி திரட்டல்'],
                ['value' => 'Furniture', 'tamil_name' => 'மரச்சாமான்கள்'],
                ['value' => 'Gambling and Casinos', 'tamil_name' => 'சூதாட்டம் மற்றும் கேசினோ'],
                ['value' => 'Glass, Ceramics and Concrete', 'tamil_name' => 'கண்ணாடி, செராமிக் மற்றும் கான்கிரீட்'],
                ['value' => 'Government Administration', 'tamil_name' => 'அரசு நிர்வாகம்'],
                ['value' => 'Government Relations', 'tamil_name' => 'அரசு தொடர்புகள்'],
                ['value' => 'Graphic Design/Web Design', 'tamil_name' => 'கிராஃபிக்/வலை வடிவமைப்பு'],
                ['value' => 'Health, Wellness and Fitness', 'tamil_name' => 'ஆரோக்கியம் மற்றும் உடற்பயிற்சி'],
                ['value' => 'Higher Education', 'tamil_name' => 'உயர் கல்வி'],
                ['value' => 'Hospital and Health Care', 'tamil_name' => 'மருத்துவமனை மற்றும் சுகாதார பராமரிப்பு'],
                ['value' => 'Hospitality', 'tamil_name' => 'விருந்தோம்பல்'],
                ['value' => 'Human Resources', 'tamil_name' => 'மனிதவள மேலாண்மை'],
                ['value' => 'Import and Export', 'tamil_name' => 'இறக்குமதி மற்றும் ஏற்றுமதி'],
                ['value' => 'Individual and Family Services', 'tamil_name' => 'தனிப்பட்ட மற்றும் குடும்ப சேவைகள்'],
                ['value' => 'Industrial Automation', 'tamil_name' => 'தொழில்துறை தானியங்கி அமைப்புகள்'],
                ['value' => 'Information Services', 'tamil_name' => 'தகவல் சேவைகள்'],
                ['value' => 'Information Technology and Services', 'tamil_name' => 'தகவல் தொழில்நுட்பம் மற்றும் சேவைகள்'],
                ['value' => 'Insurance', 'tamil_name' => 'காப்பீடு'],
                ['value' => 'International Affairs', 'tamil_name' => 'சர்வதேச விவகாரங்கள்'],
                ['value' => 'International Trade and Development', 'tamil_name' => 'சர்வதேச வர்த்தகம் மற்றும் வளர்ச்சி'],
                ['value' => 'Internet', 'tamil_name' => 'இணையம்'],
                ['value' => 'Investment Banking/Venture Capital/Private Equity', 'tamil_name' => 'முதலீட்டு வங்கி/தொழில் முதலீடு/தனியார் பங்கு'],
                ['value' => 'Judiciary Office/Legal', 'tamil_name' => 'நீதித்துறை/சட்டம்']
            ],


            'hobbies' => [
                ['value' => 'Reading', 'tamil_name' => 'படித்தல்'],
                ['value' => 'Traveling', 'tamil_name' => 'பயணம்'],
                ['value' => 'Cooking', 'tamil_name' => 'சமையல்'],
                ['value' => 'Sports', 'tamil_name' => 'விளையாட்டு'],
                ['value' => 'Music', 'tamil_name' => 'இசை'],
                ['value' => 'Movies', 'tamil_name' => 'திரைப்படங்கள்'],
                ['value' => 'Hiking', 'tamil_name' => 'மலையேறும் நடைபயணம்'],
                ['value' => 'Dancing', 'tamil_name' => 'நடனம்'],
                ['value' => 'Gardening', 'tamil_name' => 'தோட்டக்கலை'],
                ['value' => 'Photography', 'tamil_name' => 'புகைப்படம்'],
                ['value' => 'Writing', 'tamil_name' => 'எழுத்து'],
                ['value' => 'Yoga', 'tamil_name' => 'யோகா'],
                ['value' => 'Fishing', 'tamil_name' => 'மீன்பிடி'],
                ['value' => 'Crafting', 'tamil_name' => 'கைவினை'],
                ['value' => 'Gaming', 'tamil_name' => 'விளையாட்டு'],
                ['value' => 'Volunteering', 'tamil_name' => 'தன்னார்வ சேவை'],
                ['value' => 'Collecting', 'tamil_name' => 'சேகரித்தல்'],
                ['value' => 'Meditation', 'tamil_name' => 'தியானம்'],
                ['value' => 'Cycling', 'tamil_name' => 'மிதிவண்டி ஓட்டம்'],
                ['value' => 'Fitness', 'tamil_name' => 'உடற்பயிற்சி'],
                ['value' => 'Drawing', 'tamil_name' => 'வரைதல்'],
                ['value' => 'Painting', 'tamil_name' => 'ஓவியம்'],
                ['value' => 'Knitting', 'tamil_name' => 'நூலோட்டம்'],
                ['value' => 'Sewing', 'tamil_name' => 'தையல்'],
                ['value' => 'Woodworking', 'tamil_name' => 'மர வேலை'],
                ['value' => 'Bird Watching', 'tamil_name' => 'பறவைகள் பார்வை'],
                ['value' => 'Astronomy', 'tamil_name' => 'வானியல்'],
                ['value' => 'Puzzles', 'tamil_name' => 'பழுதுபார்த்தல்'],
                ['value' => 'Board Games', 'tamil_name' => 'பலகை விளையாட்டுகள்'],
                ['value' => 'Martial Arts', 'tamil_name' => 'மார்ஷியல் கலை'],
                ['value' => 'Surfing', 'tamil_name' => 'அலை ஓட்டம்'],
                ['value' => 'Skiing', 'tamil_name' => 'பனியில் சறுக்கல்'],
                ['value' => 'Snowboarding', 'tamil_name' => 'பனியில் சறுக்கும் பலகை'],
                ['value' => 'Travel Blogging', 'tamil_name' => 'பயண பதிவுகள்'],
                ['value' => 'Blogging', 'tamil_name' => 'வலைப்பதிவு'],
                ['value' => 'Podcasting', 'tamil_name' => 'பாட்காஸ்ட்'],
                ['value' => 'Home Brewing', 'tamil_name' => 'வீட்டில் பானம் தயாரித்தல்'],
                ['value' => 'Genealogy', 'tamil_name' => 'வம்ச வரலாறு'],
                ['value' => 'Calligraphy', 'tamil_name' => 'அழகான எழுத்து'],
                ['value' => 'Other', 'tamil_name' => 'மற்றவை']
            ],

            'interests' => [
                ['value' => 'Reading', 'tamil_name' => 'படித்தல்'],
                ['value' => 'Traveling', 'tamil_name' => 'பயணம்'],
                ['value' => 'Cooking', 'tamil_name' => 'சமையல்'],
                ['value' => 'Sports', 'tamil_name' => 'விளையாட்டு'],
                ['value' => 'Music', 'tamil_name' => 'இசை'],
                ['value' => 'Movies', 'tamil_name' => 'திரைப்படங்கள்'],
                ['value' => 'Hiking', 'tamil_name' => 'மலையேறும் நடைபயணம்'],
                ['value' => 'Dancing', 'tamil_name' => 'நடனம்'],
                ['value' => 'Gardening', 'tamil_name' => 'தோட்டக்கலை'],
                ['value' => 'Photography', 'tamil_name' => 'புகைப்படம்'],
                ['value' => 'Writing', 'tamil_name' => 'எழுத்து'],
                ['value' => 'Yoga', 'tamil_name' => 'யோகா'],
                ['value' => 'Fishing', 'tamil_name' => 'மீன்பிடி'],
                ['value' => 'Crafting', 'tamil_name' => 'கைவினை'],
                ['value' => 'Gaming', 'tamil_name' => 'விளையாட்டு'],
                ['value' => 'Volunteering', 'tamil_name' => 'தன்னார்வ சேவை'],
                ['value' => 'Collecting', 'tamil_name' => 'சேகரித்தல்'],
                ['value' => 'Meditation', 'tamil_name' => 'தியானம்'],
                ['value' => 'Cycling', 'tamil_name' => 'மிதிவண்டி ஓட்டம்'],
                ['value' => 'Fitness', 'tamil_name' => 'உடற்பயிற்சி'],
                ['value' => 'Drawing', 'tamil_name' => 'வரைதல்'],
                ['value' => 'Painting', 'tamil_name' => 'ஓவியம்'],
                ['value' => 'Knitting', 'tamil_name' => 'நூலோட்டம்'],
                ['value' => 'Sewing', 'tamil_name' => 'தையல்'],
                ['value' => 'Woodworking', 'tamil_name' => 'மர வேலை'],
                ['value' => 'Bird Watching', 'tamil_name' => 'பறவைகள் பார்வை'],
                ['value' => 'Astronomy', 'tamil_name' => 'வானியல்'],
                ['value' => 'Puzzles', 'tamil_name' => 'பழுதுபார்த்தல்'],
                ['value' => 'Board Games', 'tamil_name' => 'பலகை விளையாட்டுகள்'],
                ['value' => 'Martial Arts', 'tamil_name' => 'மார்ஷியல் கலை'],
                ['value' => 'Surfing', 'tamil_name' => 'அலை ஓட்டம்'],
                ['value' => 'Skiing', 'tamil_name' => 'பனியில் சறுக்கல்'],
                ['value' => 'Snowboarding', 'tamil_name' => 'பனியில் சறுக்கும் பலகை'],
                ['value' => 'Travel Blogging', 'tamil_name' => 'பயண பதிவுகள்'],
                ['value' => 'Blogging', 'tamil_name' => 'வலைப்பதிவு'],
                ['value' => 'Podcasting', 'tamil_name' => 'பாட்காஸ்ட்'],
                ['value' => 'Home Brewing', 'tamil_name' => 'வீட்டில் பானம் தயாரித்தல்'],
                ['value' => 'Genealogy', 'tamil_name' => 'வம்ச வரலாறு'],
                ['value' => 'Calligraphy', 'tamil_name' => 'அழகான எழுத்து'],
                ['value' => 'Other', 'tamil_name' => 'மற்றவை']
            ],


            'cuisines' => [
                ['value' => 'Italian', 'tamil_name' => 'இத்தாலிய உணவு'],
                ['value' => 'Chinese', 'tamil_name' => 'சீன உணவு'],
                ['value' => 'Indian', 'tamil_name' => 'இந்திய உணவு'],
                ['value' => 'Mexican', 'tamil_name' => 'மெக்ஸிகன் உணவு'],
                ['value' => 'Japanese', 'tamil_name' => 'ஜப்பானிய உணவு'],
                ['value' => 'Mediterranean', 'tamil_name' => 'மத்திய தரைக்கடல் உணவு'],
                ['value' => 'Thai', 'tamil_name' => 'தாய் உணவு'],
                ['value' => 'French', 'tamil_name' => 'பிரஞ்சு உணவு'],
                ['value' => 'Spanish', 'tamil_name' => 'ஸ்பானிஷ் உணவு'],
                ['value' => 'Greek', 'tamil_name' => 'கிரேக்கம் உணவு'],
                ['value' => 'Lebanese', 'tamil_name' => 'லெபனீஸ் உணவு'],
                ['value' => 'Turkish', 'tamil_name' => 'துருக்கி உணவு'],
                ['value' => 'Vietnamese', 'tamil_name' => 'வியட்நாமிய உணவு'],
                ['value' => 'Korean', 'tamil_name' => 'கொரிய உணவு'],
                ['value' => 'Caribbean', 'tamil_name' => 'கரிபியன் உணவு'],
                ['value' => 'Ethiopian', 'tamil_name' => 'எத்தியோப்பிய உணவு'],
                ['value' => 'Moroccan', 'tamil_name' => 'மொரோக்கன் உணவு'],
                ['value' => 'German', 'tamil_name' => 'ஜெர்மன் உணவு'],
                ['value' => 'Brazilian', 'tamil_name' => 'பிரேசிலிய உணவு'],
                ['value' => 'Cuban', 'tamil_name' => 'கியூபன் உணவு']
            ],


            'foodPreferences' => [
                ['value' => 'Italian', 'tamil_name' => 'இத்தாலிய உணவு'],
                ['value' => 'Chinese', 'tamil_name' => 'சீன உணவு'],
                ['value' => 'Indian', 'tamil_name' => 'இந்திய உணவு'],
                ['value' => 'Mexican', 'tamil_name' => 'மெக்ஸிகன் உணவு'],
                ['value' => 'Japanese', 'tamil_name' => 'ஜப்பானிய உணவு'],
                ['value' => 'Mediterranean', 'tamil_name' => 'மத்திய தரைக்கடல் உணவு'],
                ['value' => 'Thai', 'tamil_name' => 'தாய் உணவு'],
                ['value' => 'French', 'tamil_name' => 'பிரஞ்சு உணவு'],
                ['value' => 'Spanish', 'tamil_name' => 'ஸ்பானிஷ் உணவு'],
                ['value' => 'Greek', 'tamil_name' => 'கிரேக்கம் உணவு'],
                ['value' => 'Lebanese', 'tamil_name' => 'லெபனீஸ் உணவு'],
                ['value' => 'Turkish', 'tamil_name' => 'துருக்கி உணவு'],
                ['value' => 'Vietnamese', 'tamil_name' => 'வியட்நாமிய உணவு'],
                ['value' => 'Korean', 'tamil_name' => 'கொரிய உணவு'],
                ['value' => 'Caribbean', 'tamil_name' => 'கரிபியன் உணவு'],
                ['value' => 'Ethiopian', 'tamil_name' => 'எத்தியோப்பிய உணவு'],
                ['value' => 'Moroccan', 'tamil_name' => 'மொரோக்கன் உணவு'],
                ['value' => 'German', 'tamil_name' => 'ஜெர்மன் உணவு'],
                ['value' => 'Brazilian', 'tamil_name' => 'பிரேசிலிய உணவு'],
                ['value' => 'Cuban', 'tamil_name' => 'கியூபன் உணவு']
            ],

            'musicGenres' => [
                ['value' => 'Carnatic', 'tamil_name' => 'கர்நாடக இசை'],
                ['value' => 'Western', 'tamil_name' => 'மேற்கு இசை'],
                ['value' => 'Bollywood', 'tamil_name' => 'பாலிவுட் இசை'],
                ['value' => 'Folk', 'tamil_name' => 'நாட்டுப்புற இசை'],
                ['value' => 'Pop', 'tamil_name' => 'பாப் இசை'],
                ['value' => 'Rock', 'tamil_name' => 'ராக் இசை'],
                ['value' => 'Hip Hop', 'tamil_name' => 'ஹிப் ஹாப்'],
                ['value' => 'Electronic', 'tamil_name' => 'மின்னணு இசை'],
                ['value' => 'R&B', 'tamil_name' => 'ஆர் & பி'],
                ['value' => 'Country', 'tamil_name' => 'கண்ட்ரி இசை'],
                ['value' => 'Jazz', 'tamil_name' => 'ஜாஸ்'],
                ['value' => 'Classical', 'tamil_name' => 'சாதாரண இசை']
            ],


            'sportsFitness' => [
                ['value' => 'Football', 'tamil_name' => 'கால்பந்து'],
                ['value' => 'Basketball', 'tamil_name' => 'கூடைப்பந்து'],
                ['value' => 'Tennis', 'tamil_name' => 'டென்னிஸ்'],
                ['value' => 'Golf', 'tamil_name' => 'கோல்ஃப்'],
                ['value' => 'Cricket', 'tamil_name' => 'கிரிக்கெட்'],
                ['value' => 'Swimming', 'tamil_name' => 'நீச்சல்'],
                ['value' => 'Athletics', 'tamil_name' => 'ஓட்டம் மற்றும் பாய்ச்சி'],
                ['value' => 'Cycling', 'tamil_name' => 'மிதிவண்டி ஓட்டம்'],
                ['value' => 'Gymnastics', 'tamil_name' => 'உடற்கல்வி'],
                ['value' => 'Boxing', 'tamil_name' => 'முத்துசண்டை'],
                ['value' => 'Wrestling', 'tamil_name' => 'போர்த்தல்'],
                ['value' => 'Skiing', 'tamil_name' => 'பனியில் சறுக்கல்'],
                ['value' => 'Snowboarding', 'tamil_name' => 'பனியில் பலகை சறுக்கல்'],
                ['value' => 'Surfing', 'tamil_name' => 'அலை ஓட்டம்'],
                ['value' => 'Yoga', 'tamil_name' => 'யோகா'],
                ['value' => 'Pilates', 'tamil_name' => 'பிலாட்டிஸ்'],
                ['value' => 'Martial Arts', 'tamil_name' => 'மார்ஷியல் கலை'],
                ['value' => 'Weightlifting', 'tamil_name' => 'எடை தூக்குதல்'],
                ['value' => 'CrossFit', 'tamil_name' => 'கிராஸ்ஃபிட்'],
                ['value' => 'Hiking', 'tamil_name' => 'மலையேறும் நடைபயணம்'],
                ['value' => 'Soccer', 'tamil_name' => 'சாக்கர்'],
                ['value' => 'Baseball', 'tamil_name' => 'பெஸ்பால்'],
                ['value' => 'Volleyball', 'tamil_name' => 'வாலிபால்'],
                ['value' => 'Handball', 'tamil_name' => 'கைபந்து'],
                ['value' => 'Hockey', 'tamil_name' => 'ஹாக்கி'],
                ['value' => 'Rugby', 'tamil_name' => 'ரக்பி'],
                ['value' => 'Lacrosse', 'tamil_name' => 'லக்ரோஸ்'],
                ['value' => 'Table Tennis', 'tamil_name' => 'மேசை டென்னிஸ்'],
                ['value' => 'Badminton', 'tamil_name' => 'பாட்மின்டன்'],
                ['value' => 'Fencing', 'tamil_name' => 'வாள் சண்டை'],
                ['value' => 'Archery', 'tamil_name' => 'அம்பு வீச்சு'],
                ['value' => 'Gym', 'tamil_name' => 'உடற்பயிற்சி மையம்'],
                ['value' => 'Other', 'tamil_name' => 'மற்றவை']
            ],


            'petPreferences' => [
                ['value' => 'Dog', 'tamil_name' => 'நாய்'],
                ['value' => 'Cat', 'tamil_name' => 'பூனை'],
                ['value' => 'Bird', 'tamil_name' => 'பறவை'],
                ['value' => 'Fish', 'tamil_name' => 'மீன்'],
                ['value' => 'Reptile', 'tamil_name' => 'உரோமி விலங்கு'],
                ['value' => 'Rodent', 'tamil_name' => 'எலி வகை'],
                ['value' => 'Horse', 'tamil_name' => 'குதிரை'],
                ['value' => 'No Pets', 'tamil_name' => 'விலங்குகள் இல்லை'],
                ['value' => 'Other', 'tamil_name' => 'மற்றவை']
            ],


            'travelPreferences' => [
                ['value' => 'Adventure', 'tamil_name' => 'சாகசம்'],
                ['value' => 'Wildlife', 'tamil_name' => 'விலங்குகள் பார்வை'],
                ['value' => 'Beaches', 'tamil_name' => 'கடற்கரை'],
                ['value' => 'Cities', 'tamil_name' => 'நகரங்கள்'],
                ['value' => 'Mountains', 'tamil_name' => 'மலைகள்'],
                ['value' => 'Countryside', 'tamil_name' => 'புறநகர்'],
                ['value' => 'Cruise', 'tamil_name' => 'கப்பல் பயணம்'],
                ['value' => 'Road Trip', 'tamil_name' => 'சாலை பயணம்'],
                ['value' => 'Cultural', 'tamil_name' => 'கலாசார பயணம்'],
                ['value' => 'Relaxation', 'tamil_name' => 'ஓய்வு பயணம்'],
                ['value' => 'Other', 'tamil_name' => 'மற்றவை']
            ],


            'familyStatus' => [
                ['value' => 'Middle Class', 'tamil_name' => 'நடுத்தர வர்க்கம்'],
                ['value' => 'Upper Middle Class', 'tamil_name' => 'மேல் நடுத்தர வர்க்கம்'],
                ['value' => 'Rich', 'tamil_name' => 'பெரியவர்'],
                ['value' => 'Other', 'tamil_name' => 'மற்றவை']
            ],

            'physicalStatus' => [
                ['value' => 'Normal', 'tamil_name' => 'சாதம்'],
                ['value' => 'Physically Challenged', 'tamil_name' => 'உடல் நலக்குறைவு']
            ],

            'zodiacs' => [
                ['value' => 'Aries', 'tamil_name' => 'மேஷம்'],
                ['value' => 'Taurus', 'tamil_name' => 'ரிஷபம்'],
                ['value' => 'Gemini', 'tamil_name' => 'மிதுனம்'],
                ['value' => 'Cancer', 'tamil_name' => 'கடகம்'],
                ['value' => 'Leo', 'tamil_name' => 'சிம்மம்'],
                ['value' => 'Virgo', 'tamil_name' => 'கன்னி'],
                ['value' => 'Libra', 'tamil_name' => 'துலாம்'],
                ['value' => 'Scorpio', 'tamil_name' => 'விருச்சிகம்'],
                ['value' => 'Sagittarius', 'tamil_name' => 'தனுசு'],
                ['value' => 'Capricorn', 'tamil_name' => 'மகரம்'],
                ['value' => 'Aquarius', 'tamil_name' => 'கும்பம்'],
                ['value' => 'Pisces', 'tamil_name' => 'மீனம்'],
            ],

            'birth_star' => [
                ['value' => 'Ashwini', 'tamil_name' => 'அசுவினி'],
                ['value' => 'Bharani', 'tamil_name' => 'பரணி'],
                ['value' => 'Krittika', 'tamil_name' => 'கிருத்திகை'],
                ['value' => 'Rohini', 'tamil_name' => 'ரோகிணி'],
                ['value' => 'Mrigashirsha', 'tamil_name' => 'மிருகசிரீஷம்'],
                ['value' => 'Ardra', 'tamil_name' => 'திருவாதிரை'],
                ['value' => 'Punarvasu', 'tamil_name' => 'புனர்பூசம்'],
                ['value' => 'Pushya', 'tamil_name' => 'பூசம்'],
                ['value' => 'Ashlesha', 'tamil_name' => 'ஆயில்யம்'],
                ['value' => 'Magha', 'tamil_name' => 'மகம்'],
                ['value' => 'Purva Phalguni', 'tamil_name' => 'பூரம்'],
                ['value' => 'Uttara Phalguni', 'tamil_name' => 'உத்திரம்'],
                ['value' => 'Hasta', 'tamil_name' => 'ஹஸ்தம்'],
                ['value' => 'Chitra', 'tamil_name' => 'சித்திரை'],
                ['value' => 'Swati', 'tamil_name' => 'சுவாதி'],
                ['value' => 'Vishakha', 'tamil_name' => 'விசாகம்'],
                ['value' => 'Anuradha', 'tamil_name' => 'அனுஷம்'],
                ['value' => 'Jyeshtha', 'tamil_name' => 'கேட்டை'],
                ['value' => 'Mula', 'tamil_name' => 'மூலம்'],
                ['value' => 'Purva Ashadha', 'tamil_name' => 'பூராடம்'],
                ['value' => 'Uttara Ashadha', 'tamil_name' => 'உத்திராடம்'],
                ['value' => 'Shravana', 'tamil_name' => 'திருவோணம்'],
                ['value' => 'Dhanishta', 'tamil_name' => 'அவிட்டம்'],
                ['value' => 'Shatabhisha', 'tamil_name' => 'சதயம்'],
                ['value' => 'Purva Bhadrapada', 'tamil_name' => 'பூரட்டாதி'],
                ['value' => 'Uttara Bhadrapada', 'tamil_name' => 'உத்திரட்டாதி'],
                ['value' => 'Revati', 'tamil_name' => 'ரேவதி'],
            ],

            'genders' => [
                ['value' => 'Male', 'tamil_name' => 'ஆண்'],
                ['value' => 'Female', 'tamil_name' => 'பெண்'],
                ['value' => 'Other', 'tamil_name' => 'மற்றவை'],
            ],

            "jobs"=> [
                ['value' => "Doctor", 'tamil_name' => 'மருத்துவர்'],
                ['value' => "VIP", 'tamil_name' => 'முக்கிய நபர்'],
                ['value' => "Engineer", 'tamil_name' => 'பொறியாளர்'],
                ['value' => "Pilot", 'tamil_name' => 'பைலட்'],
                ['value' => "Nurse", 'tamil_name' => 'நர்ஸ்'],
                ['value' => "Pharmacist", 'tamil_name' => 'மருந்தாளர்'],
                ['value' => "Lawyer", 'tamil_name' => 'வக்கீல்'],
                ['value' => "Artist", 'tamil_name' => 'கலைஞர்'],
                ['value' => "Scientist", 'tamil_name' => 'அறிவியலாளர்'],
                ['value' => "Actor / Actress", 'tamil_name' => 'நடிகர் / நடிகை'],
                ['value' => "Architect", 'tamil_name' => 'கட்டிடக்கலைஞர்'],
                ['value' => "Chef", 'tamil_name' => 'சமையல்காரர்'],
                ['value' => "Civil Services", 'tamil_name' => 'சிவில் சேவைகள்'],
                ['value' => "Consultant", 'tamil_name' => 'ஆலோசகர்'],
                ['value' => "Designer", 'tamil_name' => 'வடிவமைப்பாளர்'],
                ['value' => "Economist", 'tamil_name' => 'பொருளாதார நிபுணர்'],
                ['value' => "Farmer", 'tamil_name' => 'விவசாயி'],
                ['value' => "Journalist", 'tamil_name' => 'செய்தியாளர்'],
                ['value' => "Judge", 'tamil_name' => 'நீதிபதி'],
                ['value' => "Lecturer / Professor", 'tamil_name' => 'உபாத்யாயர் / பேராசிரியர்'],
                ['value' => "Manager", 'tamil_name' => 'மேலாளர்'],
                ['value' => "Marketing Professional", 'tamil_name' => 'மார்க்கெட்டிங் நிபுணர்'],
                ['value' => "Media Professional", 'tamil_name' => 'மீடியா நிபுணர்'],
                ['value' => "Military", 'tamil_name' => 'படைப்பிரிவு'],
                ['value' => "Musician", 'tamil_name' => 'இசையமைப்பாளர்'],
                ['value' => "Politician", 'tamil_name' => 'அரசியல்வாதி'],
                ['value' => "Foreign", 'tamil_name' => 'வெளிநாட்டு'],
                ['value' => "Real Estate Professional", 'tamil_name' => 'உயர் நிலம் வியாபாரி'],
                ['value' => "Researcher", 'tamil_name' => 'ஆராய்ச்சியாளர்'],
                ['value' => "Sales Professional", 'tamil_name' => 'விற்பனை நிபுணர்'],
                ['value' => "Social Worker", 'tamil_name' => 'சமூக பணியாளர்'],
                ['value' => "Sports Professional", 'tamil_name' => 'விளையாட்டு நிபுணர்'],
                ['value' => "Technician", 'tamil_name' => 'தொழில்நுட்ப வல்லுநர்'],
                ['value' => "Writer", 'tamil_name' => 'எழுத்தாளர்'],
                ['value' => "Govt Job", 'tamil_name' => 'அரசு வேலை'],
                ['value' => "Bank", 'tamil_name' => 'வங்கி'],
                ['value' => "Businessman", 'tamil_name' => 'வணிகர்'],
                ['value' => "Accountant", 'tamil_name' => 'கணக்காளர்'],
                ['value' => "Auditor", 'tamil_name' => 'ஆடிட்டர்'],
                ['value' => "Clerk", 'tamil_name' => 'கிளார்க்'],
                ['value' => "Receptionist", 'tamil_name' => 'ரிசப்ஷனிஸ்ட்'],
                ['value' => "Secretary", 'tamil_name' => 'செயலாளர்'],
                ['value' => "Driver", 'tamil_name' => 'ஓட்டுநர்'],
                ['value' => "Pilot", 'tamil_name' => 'பைலட்'],
                ['value' => "Air Hostess", 'tamil_name' => 'ஏர் ஹோஸ்டஸ்'],
                ['value' => "Mechanic", 'tamil_name' => 'மேக்கானிக்'],
                ['value' => "Electrician", 'tamil_name' => 'மின்சார தொழில்நுட்ப வல்லுநர்'],
                ['value' => "Plumber", 'tamil_name' => 'பிளம்பர்'],
                ['value' => "Carpenter", 'tamil_name' => 'மரக்காரர்'],
                ['value' => "Security Personnel", 'tamil_name' => 'பாதுகாப்பு பணியாளர்'],
                ['value' => "Hotel Staff", 'tamil_name' => 'ஹோட்டல் பணியாளர்'],
                ['value' => "Retail Staff", 'tamil_name' => 'சில்லறை விற்பனை பணியாளர்'],
                ['value' => "Factory Worker", 'tamil_name' => 'கூலை தொழிலாளி'],
                ['value' => "Laborer", 'tamil_name' => 'தொழிலாளி'],
                ['value' => "Housewife", 'tamil_name' => 'வீட்டுக்காரி'],
                ['value' => "Unemployed", 'tamil_name' => 'வேலை இல்லாதவர்'],
                ['value' => "Student", 'tamil_name' => 'மாணவர்'],
                ['value' => "Retired", 'tamil_name' => 'ஓய்வுபெற்றவர்'],
                ['value' => "IT Company", 'tamil_name' => 'ஐடி நிறுவனம்'],
                ['value' => "Non IT / Private Company",'tami\l_name' => 'பொது / தனியார் நிறுவனம்'],
                ['value' => "Self Employed", 'tamil_name' => 'சுய தொழில்'],
                ['value' => "Farmer", 'tamil_name' => 'விவசாயி'],
                ['value' => "Teacher", 'tamil_name' => 'ஆசிரியர்'],
                ['value' => "Own Business", 'tamil_name' => 'தனியார் வியாபாரம்'],
                ['value' => "Not Specified", 'tamil_name' => 'குறிப்பிடப்படவில்லை']
            ],

            "educations"=> [
                ["value"=>"Matriculation"] ,
                ["value"=>"Below 10th STD"] ,
                ["value"=>"10th STD"] ,
                ["value"=>"12th STD"] ,
                ["value"=>"ITI"] ,
                ["value"=>"Diploma"] ,
                ["value"=>"Degree - UG Arts"] ,
                ["value"=>"Degree - PG Arts"] ,
                ["value"=>"BE / B Tech"] ,
                ["value"=>"ME / M Tech / MBA"] ,
                ["value"=>"Doctor"] ,
                ["value"=>"Others"]
            ],
            "cities"=> [
                ["value"=>"Ambur","tamil_name"=>"அம்பூர்"],
                ["value"=>"Ambattur","tamil_name"=>"அம்பத்தூர்"],
                ["value"=>"Ariyalur","tamil_name"=>"அரியலூர்"],
                ["value"=>"Avadi","tamil_name"=>"ஆவடி"],
                ["value"=>"Chengalpattu","tamil_name"=>"செங்கல்பட்டு"],
                ["value"=>"Chennai","tamil_name"=>"சென்னை"],
                ["value"=>"Coimbatore","tamil_name"=>"கோயம்புத்தூர்"],
                ["value"=>"Cuddalore","tamil_name"=>"கடலூர்"],
                ["value"=>"Dharmapuri","tamil_name"=>"தர்மபுரி"],
                ["value"=>"Dindigul","tamil_name"=>"திண்டுக்கல்"],
                ["value"=>"Erode","tamil_name"=>"ஈரோடு"],
                ["value"=>"Hosur","tamil_name"=>"ஓசூர்"],
                ["value"=>"Kanyakumari","tamil_name"=>"கன்னியாகுமரி"],
                ["value"=>"Karaikkudi","tamil_name"=>"கரைக்குடி"],
                ["value"=>"Karur","tamil_name"=>"கரூர்"],
                ["value"=>"Kancheepuram","tamil_name"=>"காஞ்சிபுரம்"],
                ["value"=>"Kallakurichi","tamil_name"=>"கள்ளக்குறிச்சி"],
                ["value"=>"Krishnagiri","tamil_name"=>"கிருஷ்ணகிரி"],
                ["value"=>"Kurichi","tamil_name"=>"குறிச்சி"],
                ["value"=>"Kumbakonam","tamil_name"=>"கும்பகோணம்"],
                ["value"=>"Madurai","tamil_name"=>"மதுரை"],
                ["value"=>"Madavaram","tamil_name"=>"மாதவரம்"],
                ["value"=>"Mayiladuthurai","tamil_name"=>"மயிலாடுதுறை"],
                ["value"=>"Namakkal","tamil_name"=>"நாமக்கல்"],
                ["value"=>"Nagapattinam","tamil_name"=>"நாகப்பட்டினம்"],
                ["value"=>"Nagercoil","tamil_name"=>"நாகர்கோவில்"],
                ["value"=>"Neyveli","tamil_name"=>"நெய்வேலி"],
                ["value"=>"Nilgiri","tamil_name"=>"நீலகிரி (உதகமண்டலம்)"],
                ["value"=>"Perambalur","tamil_name"=>"பெரம்பலூர்"],
                ["value"=>"Pudukkottai","tamil_name"=>"புதுக்கோட்டை"],
                ["value"=>"Rajapalayam","tamil_name"=>"ராஜபாளையம்"],
                ["value"=>"Ranipet","tamil_name"=>"இராணிப்பேட்டை"],
                ["value"=>"Ramanathapuram","tamil_name"=>"இராமநாதபுரம்"],
                ["value"=>"Salem","tamil_name"=>"சேலம்"],
                ["value"=>"Sivaganga","tamil_name"=>"சிவகங்கை"],
                ["value"=>"Tambaram","tamil_name"=>"தாம்பரம்"],
                ["value"=>"Tenkasi","tamil_name"=>"தென்காசி"],
                ["value"=>"Thanjavur","tamil_name"=>"தஞ்சாவூர்"],
                ["value"=>"Theni","tamil_name"=>"தேனி"],
                ["value"=>"Thirupathur","tamil_name"=>"திருப்பத்தூர்"],
                ["value"=>"Thiruvallur","tamil_name"=>"திருவள்ளூர்"],
                ["value"=>"Tiruvannamalai","tamil_name"=>"திருவண்ணாமலை"],
                ["value"=>"Tiruvottiyur","tamil_name"=>"திருவொற்றியூர்"],
                ["value"=>"Tiruchirappalli","tamil_name"=>"திருச்சிராப்பள்ளி"],
                ["value"=>"Tirunelveli","tamil_name"=>"திருநெல்வேலி"],
                ["value"=>"Tiruppur","tamil_name"=>"திருப்பூர்"],
                ["value"=>"Thoothukkudi","tamil_name"=>"தூத்துக்குடி"],
                ["value"=>"Thiruvarur","tamil_name"=>"திருவாரூர்"],
                ["value"=>"Viluppuram","tamil_name"=>"விழுப்புரம்"],
                ["value"=>"Vellore","tamil_name"=>"வேலூர்"],
                ["value"=>"Vaniyambadi","tamil_name"=>"வாணியம்பாடி"],
                ["value"=>"Pudukkottai","tamil_name"=>"புதுக்கோட்டை"],
                ["value"=>"Other","tamil_name"=>"மற்றவை"]
            ]

        ];
        
        // Clear existing data to prevent duplicates on re-seeding
        // This is optional, but good practice if you want a clean slate each time
        ReferenceData::truncate(); 
        // Note: If you uncomment truncate, ensure you handle foreign key constraints if any.


        foreach ($data as $type => $values) {
            foreach ($values as $item) {
                ReferenceData::create([
                    'type' => $type,
                    'value' => $item['value'],
                    'tamil_name' => $item['tamil_name'] ?? null, // fallback if missing
                ]);
            }
        }        
    }
}
